mvcweb/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcweb.Controllers
{
    public class TeacherController : Controller
    {


        public ActionResult ChangePassword()
        {
            return View();
        }

        public ActionResult CourseList()
        {
            return View();
        }

        public ActionResult CourseTable()
        {
            return View();
        }

        public ActionResult Evaluate()
        {
            return View();
        }


    }
}

mvcweb/Views/Teacher/ChangePassword.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChangePassword</title>
    <link href="~/assets/css/common.css" rel="stylesheet" />
    <link href="~/assets/css/teacher.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("TeacherNav", 0)

    <!--修改密码-->
    <div class="section">
        <div class="ad">
            <div class="container ">
                <div class="page-title">
                    <h1>Password Reset</h1>
                    <div class="divider"></div>
                </div>
                <div class="safe member-page-content">
                    <div class="single-body">
                        <div class="form-group" style="height: 50px; margin-top: 36px">
                            <label class="label" style="float: left; width:150px;">Old Password：</label>
                            <input type="password" name="pwd" class="input flt" style=" width: 300px;" @*placeholder="Please enter the old password"*@ />
                        </div>

                        <div class="form-group" style="height: 60px;">
                            <label class="label" style="float: left; width: 150px;"><span id="name">New Password：</span></label>
                            <input type="password" name="newpwd" class="input flt" style=" width: 300px;" @*placeholder="Please enter a new password"*@ />
                            <div class="descibe flt" style="font-size: 12px; padding-left: 166px; margin-right: -200px;">Password must be based on numbers, letters or characters, and not less than six</div>
                        </div>
                        <div class="form-group" style="height: 50px;">
                            <label class="label" style="float: left; width: 150px;">confirm password：</label>
                            <input type="password" name="confirmpwd" class="input flt" style=" width: 300px;" @*placeholder="Enter the new password again"*@ />
                            <div class="descibe flt" style="font-size: 12px; padding-left: 166px; margin-right: -200px;">Confirm Password with the new password must be the same</div>
                        </div>
                        <div class="form-group" style="height: 50px;">
                            <button method="updatePassword" class="btn middle" style="margin-left: 170px; margin-top: 7px; ">save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/js/teachermember.js"></script>
    <script>
        $(function () {
            if (window.top && window.top.updateContentFrameHeight) {
                window.top.updateContentFrameHeight(document.body.scrollHeight);
            }
            member.safeReady();
        });
    </script>
</body>
</html>

mvcweb/Views/Teacher/CourseList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CourseList</title>
    <link href="~/assets/css/common.css" rel="stylesheet" />
    <link href="~/assets/css/teacher.css" rel="stylesheet" />
    <link href="~/assets/css/table.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("TeacherNav", 1)
    <div class="section">
        <div class="ad">
            <div class="container courselist">
                <div class="page-title">
                    <h1>My Classes</h1>
                    <div class="divider"></div>
                    <ul class="tab nav-tabs">
                        <li class="focus  hidden" data="3">study plan</li>
                        <li data="0" class="hide3  hidden">offer lessons</li>
                        <li data="1">To be in class</li>
                        <li data="2">History lessons</li>
                    </ul>
                </div>
                <div class="">
                    <div class="courselist-div">
                        <div class="courselist_table_container">
                            <table class="course_yueke" cellspacing="0">
                                <colgroup>
                                    <col width="15%" />
                                    <col width="13%" />
                                    <col width="15%" />
                                    <col width="12%" />
                                    <col width="10%" />
                                    <col width="20%" />
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>Class Type</th>
                                        <th>Class Level</th>
                                        <th>Subject</th>
                                        <th>Class Mode</th>
                                        <th>Progress</th>
                                        <th>Evaluation</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                        <div style="width: 100%; height: 60px;">
                            <div class="page"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- 课程详情 -->
    <div class="classhour hidden">
        <table class="course_yueke">
            <thead>
                <tr>
                    <th>Lesson times</th>
                    <th style="width: 113px;">School teacher</th>
                    @*<th style="width: 113px;">School manager</th>*@
                    <th>Booked/Reducible</th>
                    <th>Class time</th>
                    <th>Duration</th>
                    <th>Status</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div class="page"></div>
    </div>
    <div class="classEvaluate hidden">
        <div class="remark flt" style="width: 400px; height: 125px;">
        </div>
        <div class="flt" style="width: 400px; height: 120px;">
            <label class="label flt" style="height: 120px; width: 120px; line-height: 120px;">Evaluation：</label>
            <textarea class="evaluatecontent flt" style="height: 120px; width: 260px;"></textarea>
        </div>
        <div style="width: 400px; height: 20px; float: left;">
            <a class="btntiny frt" style="margin-top: 20px; margin-right: 30px;" action="evaluate">submit</a>
        </div>
    </div>

    <!--查看课件-->
    <div class="lessonaccess hidden">
        <table class="course_yueke">
            <thead>
                <tr>
                    <td>No.</td>
                    <td>Lesson No.</td>
                    <td>Lesson Name</td>
                    <td>Courseware name</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <!--智能约课-->
    <div class="courseyuyue hidden flt" style="height: 810px;">
        <div class="content_title">
            <div class="title flt">VIP1 of 1 English Package courses</div>
        </div>
        <div class="content_left flt">
            <ul class="ul_yueke_left">
                <li style="height: 33px;">
                    <div class="list_text">
                        <div class="label flt">
                            type of reservation:
                        </div>
                        <div class="container flt">
                            <div class="selbtn select flt" action="mode" data="1">By time</div>
                            <div class="selbtn flt" action="mode" data="2">By teacher</div>
                        </div>
                    </div>
                </li>
                <li style="height: 33px;">
                    <div class="list_text">
                        <div class="label flt">
                            number of classes:
                        </div>
                        <div class="container flt">
                            <div class="selbtn select flt" action="times" data="1">reserve class by time</div>
                            <div class="selbtn flt" action="times" data="2">Even about two lessons</div>
                            <div class="selbtn flt" action="times" data="3">Even about three lessons</div>
                        </div>
                    </div>
                </li>
                <li style="height: 30px;" class="selteacher hidden">
                    <div class="list_text">
                        <div class="label flt">Select teacher:</div>
                        <div class="input flt" style="cursor: pointer; height: 18px; color: #30a0f6; padding: 5px; margin-top: 3px; text-align: center;" action="selectTeacher">Select teacher</div>
                    </div>
                </li>
                <li style="height: 40px;">
                    <div class="list_text flt">
                        <div class="label flt" style="height: 60px; line-height: 60px;">Class Date:</div>
                        <div class="choicedate flt"></div>
                    </div>
                </li>
                <li style="height: 120px;">
                    <div class="list_text flt">
                        <div class="label">Class time:</div>
                        <div class="choicetime flt">
                        </div>
                    </div>
                </li>
                <li style="height: 30px;">
                    <button class="btn flt" action="submit" style="margin-left: 634px; width: 80px; height: 30px;">reservation</button>
                </li>
            </ul>
        </div>
        <div class="content_table flt">
            <ul class="previewclass">
                <li style="">
                    <div class="time flt right_border">Course type</div>
                    <div class="coursename flt right_border">Subject</div>
                    <div class="class flt right_border">Class way</div>
                    <div class="coursename flt right_border">School teacher</div>
                    <div class="class flt right_border">Class time</div>
                    <div class="operation flt">Operation</div>
                </li>
            </ul>
            <div class="page"></div>
        </div>

        <div class="win_grid hidden">
            <div style="height: 30px; padding: 5px;">
                <div class="label flt" style="width: inherit;">Name：</div>
                <input class="input flt" style="padding: 5px" type="text" />
            </div>
            <div style="width: 100%; padding: 0;">
                <table class="win_table">
                    <thead style="background-color: #ddd;">
                        <tr>
                            <th>头像</th>
                            <th>中文名称</th>
                            <th>英文名称</th>
                            <th style="width: 280px;">介绍</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="page" style="position: absolute; top: 380px; right: 10px;">
                </div>
            </div>
        </div>

    </div>


    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script src="~/js/layer/layer.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/js/teachermember.js"></script>
    <script>
        $(function () {
            if (window.top && window.top.updateContentFrameHeight) {
                window.top.updateContentFrameHeight(1200);
            }
            member.myCourseReady();
        });
    </script>
</body>

</html>

mvcweb/Views/Teacher/CourseTable.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CourseTable</title>
    <link href="~/assets/css/common.css" rel="stylesheet" />
    <link href="~/js/laydate/need/laydate.css" rel="stylesheet" />
    <link href='~/js/fullcalendar/fullcalendar.css' rel='stylesheet' />
    <link href='~/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
    <link href="~/assets/css/teacher.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("TeacherNav", 2)
    <div class="section">
        <div class="ad ad-1">
            <div class="container">
                <div class="page-title">
                    <h1>COURSE MANAGEMENT</h1>
                    <div class="divider"></div>
                </div>
                <div class="free-course">
                    <div class="coursetable flt" style="margin-left: 11px;">
                        <div class="fullcalender">
                        </div>
                        <div class="courseform hidden">
                            <table>
                                <tr>
                                    <td>课程类型：</td>
                                    <td>
                                        <div id="kclx"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>课程级别：</td>
                                    <td>
                                        <div id="kcjb"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>课程名称：</td>
                                    <td>
                                        <div id="kcmc"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>上课老师：</td>
                                    <td>
                                        <div id="skls"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>上课模式：</td>
                                    <td>
                                        <div id="skms"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>上课时间：</td>
                                    <td>
                                        <div id="sksj"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>上课时长：</td>
                                    <td>
                                        <div id="sksc"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>课次：</td>
                                    <td>
                                        <div id="kc"></div>
                                    </td>
                                </tr>
                            </table>

                            <div class="oper">
                                <a class="btn" type="1" target="_blank">进入教室</a>
                                <a class="btn" type="2">取消预约</a>
                                <a class="btn" type="3" target="_blank">视频回放</a>
                                <a class="btn" type="4" target="_blank">下载课件</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--查看课件-->
    <div class="lessonaccess hidden">
        <table class="course_yueke">
            <thead>
                <tr>
                    <td>序号</td>
                    <td>课次号</td>
                    <td>课次名称</td>
                    <td>课件名称</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    
    
    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script src="~/js/layer/layer.js"></script>
    <script src="~/js/laydate/laydate.js"></script>
    <script src='~/js/fullcalendar/lib/moment.min.js'></script>
    <script src="~/js/fullcalendar/fullcalendar.js"></script>
    <script src="~/js/fullcalendar/lang/zh-cn.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/js/teachermember.js"></script>
    <script>
        $(function () {
            if (window.top && window.top.updateContentFrameHeight) {
                window.top.updateContentFrameHeight(1200);
            }
            member.myCourseListReady();
        });
    </script>
</body>
</html>

mvcweb/Views/Teacher/Evaluate.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Evaluate</title>
    <link href="~/assets/css/common.css" rel="stylesheet" />
    <link href="~/assets/css/teacher.css" rel="stylesheet" />
    <link href="~/assets/css/table.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("TeacherNav", 3)

<div class="section">
    <div class="ad">
        <div class="container courselist myevaluate">
            <div class="page-title">
                <h1 class="content_title">Score</h1>
                <div class="divider"></div>
            </div>
            <div class="">
                <div class="courselist_table_container">
                    <table class="course_yueke">
                        <colgroup>
                            <col width="15%" />
                            <col width="13%" />
                            <col width="15%" />
                            <col width="12%" />
                            <col width="10%" />
                            <col width="20%" />
                        </colgroup>
                        <thead>
                            <tr>
                                <th>Class Type</th>
                                <th>Class Level</th>
                                <th>Subject</th>
                                <th>Class Mode</th>
                                <th>Progress</th>
                                <th>Evaluation</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    <div class="page"></div>
                </div>
                <div class="classhour hidden">
                    <table class="course_yueke">
                        <thead>
                            <tr>
                                <th>Lesson times</th>
                                <th style="width: 113px;">School teacher</th>
                                @*<th style="width: 113px;">School manager</th>*@
                                <th>Booked/Reducible</th>
                                <th>Class time</th>
                                <th>Duration</th>
                                <th>Status</th>
                                <th>Operation</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    <div class="page"></div>
                </div>
                <div class="orderlist hidden">
                    <div style="width: 100%; height: 55px;">
                        <ul class="nav-tabs tab">
                            <li data="1" style="font-size: 30px; padding: 0 5px; width: auto; height: 50px; line-height: 50px; background-image: initial;">Student Feedback</li>
                            <li data="0" style="font-size: 30px; padding: 0 5px; width: auto; height: 50px; line-height: 50px; background-image: initial; ">Teacher Comments</li>
                        </ul>
                    </div>
                    <div class="order-list" style="height: 500px">
                    </div>
                    <div style="width: 100%; height: 60px;">
                        <div class="page"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
    
    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script src="~/js/layer/layer.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/js/teachermember.js"></script>
    <script>
        $(function () {
            if (window.top && window.top.updateContentFrameHeight) {
                window.top.updateContentFrameHeight(1200);
            }
            member.myEvaluateReady();
        });
    </script>
</body>
</html>

mvcweb/Views/Teacher/TeacherNav.cshtml
<div class="nav_box">
    <ul>
        <li @(((int)Model == 0 ? " class=active" : ""))>
            <a href="@Url.Action("ChangePassword", "Teacher")">Password Reset</a>
        </li>
        <li @(((int)Model == 1 ? " class=active" : ""))>
            <a href="@Url.Action("CourseList", "Teacher")">Class History</a>
        </li>
        <li @(((int)Model == 2 ? " class=active" : ""))>
            <a href="@Url.Action("CourseTable", "Teacher")">Schedule</a>
        </li>
        <li @(((int)Model == 3 ? " class=active" : ""))>
            <a href="@Url.Action("Evaluate", "Teacher")">Score</a>
        </li>
    </ul>
</div>