mvcweb/Controllers/MemberController.cs
using System;
using System.Web.Mvc;
using mvcweb.Filters;
using Model;
using Service;
using System.Web;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using Model.ViewModel;
using System.Web.Script.Serialization;

namespace mvcweb.Controllers
{
    public class MemberController : BaseController
    {
        MemberService memberService = new MemberService();

        public ActionResult Member()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult TeacherMember()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult NoopsycheOrder()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        #region 我的卡次
        /// <summary>
        /// 我的卡次
        /// </summary>
        /// <returns></returns>
        public ActionResult GetMyCourseCard()
        {
            return Json(memberService.GetMyCourseCard(member.Id));
        }
        #endregion

        #region 我的课程

        /// <summary>
        /// 获取上课计划
        /// </summary>
        /// <returns></returns>
        public ActionResult GetClassPlan(int classType, int queryType, int courseType, int classId = 0)
        {
            if (classType == 0)
            {
                var a = memberService.GetCourseCard(member.Id, queryType, courseType);
                //a.Result.

                return Json(a);
            }
            else
                return Json(memberService.GetCourseCard(member.Id, queryType, classId, courseType));
        }

        /// <summary>
        /// 一对多 加入课程
        /// </summary>
        /// <param name="planId"></param>
        /// <param name="classId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult InsertCourse(int planId, int classId)
        {
            return Content(Common.GetRequestConent(SsoKey.GetKey(memberService.GetMember(member.Id).Result), Common.AddtoCourseUrl, "{\"CplId\":\"" + planId + "\",\"ClassId\":\"" + classId + "\"}"));
        }

        /// <summary>
        /// 添加评价
        /// </summary>
        /// <param name="classComment"></param>
        /// <returns></returns>
        public ActionResult CreateClassComment(ClassComment classComment)
        {
            classComment.MemberId = member.Id.ToString();
            classComment.CreateTime = DateTime.Now;
            bool isPublicCourse = classComment.CommentType >= 100;
            try
            {
                if (member.Type != 1)
                {
                    classComment.TeacherId = memberService.GetTeacherByMemberId(member.Id).TeacherId;
                }
            }
            catch (Exception ex)
            {

            }
            classComment.CommentType = member.Type == 1 ? 0 : 1;
            return Json(memberService.CreateClassComment(classComment, isPublicCourse));
        }

        /// <summary>
        /// 获取评价
        /// </summary>
        /// <param name="cplId"></param>
        /// <returns></returns>
        public ActionResult GetLessonComment(int cplId, bool isPublic)
        {
            return Json(memberService.GetLessonComment(cplId, member.Id, isPublic));
        }

        /// <summary>
        /// 取消预约
        /// </summary>
        /// <param name="classId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CancelYuyue(int planId, int categoryCode)
        {
            try
            {
                return Content(Common.GetRequestConent(SsoKey.GetKey(memberService.GetMember(member.Id).Result), Common.CancelOrderUrl, "{\"CategoryCode\":" + categoryCode + ",\"CplId\":" + planId + "}"));
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        /// <summary>
        /// 视频列表
        /// </summary>
        /// <param name="CplId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetVideoAccess(int cplId, int courseType)
        {
            //这个地方要判断是否是公开课还是自约课
            if (courseType == 1)//公开课
            {
                var res = new Response<string>();
                res.Result = new GenSeeService().GetUrl(cplId);
                return Json(res);
            }
            else//自约课
            {
                var res = new Response<List<VideoListModel>>();
                var ret = Common.GetRequestConent(SsoKey.GetKey(memberService.GetMember(member.Id).Result), Common.VideoAccessoryUrl, "{\"CplId\":\"" + cplId + "\",\"CourseType\":\"" + courseType + "\"}");
                var tempmodel = new JavaScriptSerializer().Deserialize<VideoInfoObject>(ret);
                if (tempmodel.Data != null && tempmodel.Data.Count > 0)
                {
                    res.Result = new List<VideoListModel>();
                    try
                    {
                        tempmodel.Data.ForEach(c =>
                        {
                            var model = new VideoListModel();
                            model.RecordStartTime = c.RecordStartTime;
                            //  url = string.Format("{0}?nickName={1}&token={2}", jr["Data"]["Url"].ToString(), jr["Data"]["Id"].ToString(), jr["Data"]["PASSWORD"].ToString());
                            model.DataUrl = string.Format("{0}?nickName={1}&token={2}", c.Url, c.Id, c.PASSWORD);
                            res.Result.Add(model);
                        });
                    }
                    catch (Exception ex)
                    { 
                    }
                }
                return Json(res);
            }
        }

        /// <summary>
        /// 下载课件
        /// </summary>
        /// <param name="CplId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetLessonAccess(string CplId)
        {
            try
            {
                return Content(Common.GetRequestConent(SsoKey.GetKey(memberService.GetMember(member.Id).Result), Common.LessonAccessoryUrl, "{\"CplId\":" + CplId + "}"));
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        /// <summary>
        /// 公开课取消占座
        /// </summary>
        /// <param name="classId"></param>
        /// <returns></returns>
        public ActionResult CancelHold(int classId)
        {
            Response<bool> res = memberService.CancelHold(classId, member.Id);
            return Json(res);
        }
        #endregion

        #region 智能约课
        /// <summary>
        /// 获取上课老师
        /// </summary>
        /// <param name="courseId"></param>
        /// <returns></returns>
        public ActionResult GetClassTeacher(int classId)
        {
            return Json(memberService.GetClassTeacher(classId));
        }

        /// <summary>
        /// 获取课程老师时段
        /// </summary>
        /// <param name="courseId"></param>
        /// <param name="TeacherId"></param>
        /// <param name="BookDate"></param>
        /// <param name="CourseCount"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetCourseTeachers(int courseId, int classId, string teacherIds, string bookDate, int courseCount)
        {
            try
            {
                var coursestring = Common.GetRequestConent(SsoKey.GetKey(memberService.GetMember(member.Id).Result), Common.CapacityUrl, "{\"MemberId\":\"" + member.Id + "\",\"CourseId\":\"" + courseId + "\",\"ClassId\":\"" + classId + "\",\"BookDate\":\"" + bookDate + "\",\"CourseCount\":" + courseCount + ",\"TeacherId\":\"" + teacherIds + "\"}");
                return Content(coursestring);

            }
            catch (Exception ex)
            {
                return Content("");
            }
        }

        /// <summary>
        /// 提交课程预约
        /// </summary>
        /// <returns></returns>
        public ActionResult Order(int courseId, string teacherIds, string bookDate, int courseCount, string beginTime, int classId)
        {
            var coursestring = Common.GetRequestConent(SsoKey.GetKey(memberService.GetMember(member.Id).Result), Common.CommitCapacityUrl, "{\"MemberId\":\"" + member.Id + "\",\"CourseId\":\"" + courseId + "\",\"ClassId\":\"" + classId + "\",\"BookDate\":\"" + bookDate + "\",\"BeginTime\":\"" + beginTime + "\",\"CourseCount\":" + courseCount + ",\"TeacherIds\":\"" + teacherIds + "\"}");
            return Content(coursestring);
        }
        #endregion

        #region 修改密码
        /// <summary>
        /// 修改密码
        /// </summary>
        /// <param name="pwd"></param>
        /// <param name="newpwd"></param>
        /// <param name="confirmpwd"></param>
        /// <returns></returns>
        public ActionResult UpdatePassword(string pwd, string newpwd)
        {
            return Json(memberService.UpdatePassword(member.Id, Common.Encrypt(pwd), Common.Encrypt(newpwd)));
        }
        #endregion

        #region 修改绑定手机号
        public ActionResult UpdatePhone(string phone, string code)
        {
            var res = new Response<bool>();
            if (Session["uuid"] == null)
            {
                res.ErrMsg = "获取验证码失败！请重试";
            }
            else
            {
                try
                {
                    res = memberService.UpdatePhone(member.Id, phone, code, Session["uuid"].ToString());
                }
                catch (Exception ex)
                {
                    res.ErrMsg = "修改绑定手机号失败！";
                    LogError(string.Format("用户{0}修改绑定手机号出错：{1}", member.Id, ex.Message.ToString()).ToString());
                }
            }
            return Json(res);
        }
        #endregion

        #region 我的课表

        /// <summary>
        /// 获取课表

mvcweb/Views/BuyClass/BuyCar.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BuyCar</title>
    <link href="~/Content/commen.css" rel="stylesheet" />
    <link href="~/Content/buycar.css" rel="stylesheet" />
    <link href="~/assets/css/common.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("UserCenterNav", 4)


    <div class="content">
        <div class="car_process"></div>
        <div style="width: 100%; float: left; font-size: 24px; margin-top: 10px; border-bottom: 2px solid #004c90">
            <div class="car_logo flt"></div>
            <div class="continue_buy flt">继续购买</div>
        </div>
        <div style="width: 100%; float: left; max-height: 490px; overflow: auto;">
            <ul class="ul_car">
                <li>
                    <div class="chk_car flt">
                    <div data_ischeck="true" style="float: left; cursor: pointer; margin-left: 20px;">全选</div>
                    <div data_ischeck="false" style="float: left; cursor: pointer; margin-left: 10px;">反选</div>
                </div>
                    <div class="car_name flt">课程名称</div>
                    <div class="car_opera frt">操作</div>
                    <div class="car_number frt">数量</div>
                    <div class="car_price frt">单价</div>
                    <div class="car_gift frt">赠品</div>
                </li>
            </ul>
        </div>
        <div class="car_bottom hidden">
            <div class="chk_car flt">
                <div data_ischeck="true" style="float: left; cursor: pointer; margin-left: 20px;">全选</div>
                <div data_ischeck="false" style="float: left; cursor: pointer; margin-left: 10px;">反选</div>
            </div>
            <div class="batch_delete flt">批量删除</div>
            <div class="frt" style="margin-right: 30px;">
                <button class="btn" method="account" style="margin-top: 10px; width: 110px;">提交订单</button>
            </div>
            <div class="frt" style="margin-right: 30px;">
                <div style="font-weight: bold; font-size: 16px; float: left;">订单总金额：</div>
                <div class="total_price flt">￥ 0 元</div>
            </div>
        </div>
        <div class="car_nogoods hidden">
            <h3>您的购物车还是空的，赶紧行动吧！您可以：</h3>
            <ul style="list-style-type: none; padding-left: 10%; font-size: 13px;">
                <li style="height:30px; line-height:30px;">看看 <a href="@Url.Action("BuyClass","BuyClass")">课程卡</a></li>
                <li style="height:30px; line-height:30px;">看看 <a href="@Url.Action("Orders","Member")">我的订单</a></li>
            </ul>
        </div>
    </div>
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/layer/layer.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/js/buycar.js"></script>

    <script>
        $(function () {
            window.top.$('#ContentFrame').css({
                height: document.body.scrollHeight
            });
        });
    </script>
</body>
</html>

mvcweb/Views/BuyClass/BuyCarSubmit.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/Content/buycarsubmit.css" rel="stylesheet" />
    <link href="~/assets/css/common.css" rel="stylesheet" />
    <title>ABC在线英语</title>
    <style>
        .btn:hover {
            background-color: #2895e8;
        }

        .btn {
            background-color: #0875c8;
        }

        .car_process {
            background-image: url('../../assets/image/car_process_2.png');
            height: 67px;
        }

        .u-tt-md {
            color: #0875c8;
        }

        .f-tar {
            text-align: right;
            background-color: #ccc;
            padding: 20px;
            border-radius: 8px;
        }
    </style>
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("UserCenterNav", 3)
    <div class="content">
        <div class="car_process"></div>
        <div class="u-tit part" style="text-indent:12px; line-height:60px;">
            <span class="u-tt-md">订单信息</span>
        </div>
        <div class="ordertable part">
            <table class="u-tabx new_tabx add_new_tx extb" style="width:100%;">
                <thead class="add_bc_nonex">
                    <tr class="odd add">
                        <th width="35%" class="add_l_p35">课程卡类型</th>
                        <th width="25%">套餐详情</th>
                        <th width="26%">购买数量</th>
                        <th>单价</th>
                    </tr>
                </thead>
                <tbody>
                    @Html.Raw(ViewBag.OrderDetails)
                </tbody>
            </table>
        </div>
        <div class="bill f-tar part">
            <div class="f-fs2" style="color:#000;">
                课程卡总数<b style="color:#f00">&nbsp;@ViewBag.Count&nbsp;</b>张&nbsp;&nbsp;&nbsp;
                金额总计：<b><i class="f-ff1">¥</i><font id="total" style="color:#f00">@ViewBag.Price</font></b>
            </div>
        </div>
        <div class="u-tit part pay">
            <ul class="uls" style="padding: 30px 250px;">
                <li class="icon weixin" title="weixin" style="width:100px;height:100px;">
                    <div class="pay_normal">
                        <input name="payMethod" checked="checked" value="weixin" type="radio" style="margin-top:32px;float:left;" />
                        <img src="~/assets/image/weixin-pay.png" height="80" width="80" style="float:left;margin-left:3px;" />
                    </div>
                </li>
                <li class="icon alipay" title="alipay" style="width:100px;height:100px;">
                    <div class="pay_normal selector">
                        <input name="payMethod" value="alipay" type="radio" style="margin-top:32px; float:left;" />
                        <img src="~/assets/image/alipay.jpg" height="80" width="80" style="float:left;margin-left:3px;" />
                    </div>
                </li>
                <li class="icon unionpay" title="unionpay" style="width:140px;height:100px;">
                    <div class="pay_normal">
                        <input name="payMethod" value="unionpay" type="radio" style="margin-top:32px;float:left;" />
                        <img src="~/assets/image/unionpay.png" height="80" width="120" style="float:left;margin-left:3px;" />
                    </div>
                </li>
            </ul>
            <div style="text-indent:12px; line-height:60px;margin-top: 70px;text-align: center;">
                <span class="u-tt-md">支付方式</span>
            </div>
        </div>


        @*<div class="m-dialog" id="orderDialog" style="display: none;">
                <div class="in" style="top: 181px;">
                    <div class="hd">
                        <a class="close" href="javascript:void(0)" title="关闭">x</a>
                        <h4 class="u-tt-md">支付结果确认</h4>
                    </div>
                    <div class="bd">
                        <div class="paying f-tac">
                            请您到新打开网银页面上进行支付，支付完成前请不要关闭该窗口。
                        </div>
                    </div>
                    <div class="ft">
                        <div class="sibmit f-tac">
                            <a class="u-btn md active w154" id="pay_successed1" href="#">我已完成支付</a>
                            <a class="u-btn md hover w154" id="pay_successed2" href="#" >付款遇到问题</a>
                        </div>
                    </div>
                </div>
            </div>*@

    </div>

    <div class="sibmit f-tac" id="payBtn" style="    padding: 0 20px 20px;">
        <input type="submit" id="tbnsubmit" class="u-btn md active jsSubmit btn" style="margin:0;line-height: initial;" value="提交订单">
    </div>

    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/base.js"></script>
    <script src="~/js/layer/layer.js"></script>
    <script src="~/js/buycarsubmit.js"></script>

    <script>
        var orderNo = "@ViewBag.OrderNo";

        $(function () {
            window.top.$('#ContentFrame').css({
                height: 1000
            }); console.log('ready')
        });

    </script>

    @*<script type="text/javascript">
             $(document).ready(function () {

                 //$("#tbnsubmit").click(function () {
                 //    var div = $("#orderDialog");
                 //    div.show();
                 //});

                 //$("#pay_successed2").click(function () {
                 //    var div = $("#orderDialog");
                 //    div.hide();
                 //});

                 //$("#pay_successed1").click(function () {
                 //    var div = $("#orderDialog");
                 //    div.hide();
                 //});

             });


        </script>*@
</body>
</html>

mvcweb/Views/BuyClass/BuyWeiXinPay.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/Content/buycarsubmit.css" rel="stylesheet" />
    <link href="~/assets/css/common.css" rel="stylesheet" />
    <title>ABC在线英语</title>
    <link href="@ViewBag.Path/Content/up_p_style.css" rel="stylesheet" />
    <link href="@ViewBag.Path/Content/commen.css" rel="stylesheet" />
    <link href="@ViewBag.Path/Content/buycarsubmit.css" rel="stylesheet" />
</head>
<body>
    <div class="banner_one"></div>
    @Html.Partial("UserCenterNav", 3)
    <div class="content">
        <div class="car_process" style="height:80px; background-image: url(@ViewBag.Path/assets/image/car_process_3.png)"></div>
        <div class="m-paycourse" style="height: 695px">
            <div class="WeChat_order paytable" style="height:40px;">
                请您及时付款，以便订单尽快获得处理！ 应付金额 <b>@ViewBag.Price</b>元
            </div>
            <div class="wx_pay clearfix">
                <h3>微信支付</h3>
                <div class="wx_paycon">
                    <div class="wx_payimg">
                        <div id="qrcode">
                            <div>
                                <img alt="二维码获取失败！点击图片重新获取" onclick="this.src='@ViewBag.Path/Home/WeiXinPayImgPath?OrderId=@ViewBag.OrderId'" src="@ViewBag.Path/Home/WeiXinPayImgPath?OrderId=@ViewBag.OrderId" height="130" width="130">

                                            <!-- <img alt="二维码获取失败！点击图片重新获取" onclick="this.src='@ViewBag.Path/Home/WeiXinPayImgPath?OrderId=@ViewBag.OrderId'" src="@ViewBag.Path/Home/WeiXinPayImgPath?OrderId=@ViewBag.OrderId" height="130" width="130"> -->


                            </div>
                        </div>

                        <span>请使用微信扫一扫，扫描二维码支付</span>
                        <span>支付完成，返回<a href="@Url.Action("Orders","Member")">我的订单</a></span>
                        <input type="hidden" id="OrderId" name="OrderId" value="@ViewBag.OrderId" />
                    </div>
                    <p><img src="@ViewBag.Path/Images/wx_img02.jpg"></p>
                </div>
            </div>
        </div>
    </div>
    @*<script src="~/Scripts/jquery-1.8.2.min.js"></script>*@
    <script src="@ViewBag.Path/js/jquery-1.8.3.min.js"></script>
    <script>
        //$().ready(function () {
        //    $("#ContentFrame", parent.document).height("740px");
        //})
        //window.ready =function () {
        //    window.parent.document.getElementById("ContentFrame").style.height = "740px";
        //    //$("#ContentFrame", parent.document).height("740px");
        //}
        if (document.addEventListener) {
            document.addEventListener("DOMContentLoaded", function () {
                document.removeEventListener("DOMContentLoaded", arguments.callee, false);
                window.parent.document.getElementById("ContentFrame").style.height = "1240px";//调用参数函数
            }, false);
        } else if (document.attachEvent) {
            document.attachEvent("onreadystatechange", function () {
                if (document.readyState === "complete") {
                    document.detachEvent("onreadystatechange", arguments.callee);
                    window.parent.document.getElementById("ContentFrame").style.height = "1240px";;
                }
            });
        }

        $(document).ready(function () {
            setInterval("ajaxstatus()", 3000);
        });

        function ajaxstatus() {
            if ($("#OrderId").val() != 0) {
                var OrderId = $("#OrderId").val();
                $.ajax({
                    url: '/BuyClass/GetOrderEnable',
                    type: "post",
                    dataType: "json",
                    data: {
                        orderId: OrderId
                    },

                    success: function (rel) {
                        //debugger;
                        //if (rel.IsSuccess) {
                        if (rel.Result) {
                            window.location.href = "/Member/Orders";
                        }
                    }
                });
            }
        }

        $(function () {
            window.top.$('#ContentFrame').css({
                height: document.body.scrollHeight
            }); 
        });

    </script>
</body>
</html>

mvcweb/Views/BuyClass/NotifyAop.cshtml
@{
    Layout = null;
}

mvcweb/Views/BuyClass/PayConfirm.cshtml
@{
    Layout = null;
}
<link href="~/Content/buycarsubmit.css" rel="stylesheet" />
<div class="m-dialog" id="orderDialog">
    <div class="in" >
        <div class="hd">
            <a class="close" href="javascript:void(0)" title="关闭">x</a>
            @*<h4 class="u-tt-md">支付结果确认</h4>*@
        </div>
        <div class="bd">
            <div class="paying f-tac">
                请您到新打开网银页面上进行支付，支付完成前请不要关闭该窗口。
            </div>
        </div>
        <div class="ft">
            <div class="sibmit f-tac">
                <a class="u-btn md active w154" id="pay_successed1" href="#">我已完成支付</a>
                <a class="u-btn md hover w154" id="pay_successed2" href="#">付款遇到问题</a>
            </div>
        </div>
    </div>
</div>
<script src="/js/jquery-1.8.3.min.js"></script>
<script src="/js/base.js"></script>
<script src="/js/layer/layer.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#pay_successed1").click(function () {
            window.parent.layer.closeAll('iframe');
            window.parent.location.href = "/Member/Member?action=orderform";
        });
        $("#pay_successed2").click(function () {
            window.parent.layer.closeAll('iframe');
        });
    });
</script>