mvcweb/Controllers/PurchaseController.cs
using System.Web;
using System.Web.Mvc;

namespace mvcweb.Controllers
{
    public class PurchaseController : BascVirtualController
    {
        //
        // GET: /Purchase/

        public ActionResult Purchase()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult CourseList()
        {
            return View();
        }

        public ActionResult CourseTable()
        {
            return View();
        }

        public ActionResult Evaluate()
        {
            return View();
        }

        public ActionResult Buy()
        {
            return View();
        }

    }
}

mvcweb/Controllers/YoungController.cs
using Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcweb.Controllers
{
    public class YoungController : BascVirtualController
    {
        //
        // GET: /Young/

        public ActionResult Feature()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult Home()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult Flow()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Free()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Index()
        {
            var usercookies = HttpContext.Request.Cookies.Get("logininfo");
            var userId = "";
            if (usercookies != null)
            {
                if (!string.IsNullOrEmpty(usercookies.Value))
                {
                    var userinfo = Common.DesEncrypt(usercookies.Value);
                    userinfo = HttpUtility.UrlDecode(userinfo, System.Text.Encoding.GetEncoding("UTF-8"));
                    var usemerminfo = JsonConvert.DeserializeObject<MemberDto>(userinfo);
                    userId = usemerminfo.Id.ToString();
                }
            }
            ViewBag.Id = userId;
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Model()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Open()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Team()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Voice()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
    }
}

mvcweb/Views/Shared/AdultNav.cshtml
<div class="nav">
    <ul style="width: 1124px;">
        <li class="@((int)Model == 0 ? "active" : "")">
            <a href="@Url.Action("Home","Home")">首页</a>
        </li>
        <li class="@((int)Model == 1 ? "active" : "")">
            <a href="@Url.Action("Open", "Open")">免费课程</a>
        </li>
        <li class="@((int)Model == 2 ? "active" : "")">
            <a href="@Url.Action("Feature", "Feature")">课程特色</a>
        </li>
        <li class="@((int)Model == 3 ? "active" : "")">
            <a href="@Url.Action("Team", "Team")">外教团队</a>
        </li>
        <li class="@((int)Model == 4 ? "active" : "")">
            <a href="@Url.Action("Free", "Free")">免费答疑</a>
        </li>
        <li class="@((int)Model == 5 ? "active" : "")">
            <a href="@Url.Action("Flow", "Flow")">上课流程</a>
        </li>
        <li class="no-border @((int)Model == 6 ? "active" : "")">
            <a href="@Url.Action("Voice", "Voice")">学员心声</a>
        </li>
        <li class="no-border @((int)Model == 7 ? "active" : "")">
            <a id="hidTab" href="@Url.Action("Buy", "Purchase")"></a>
        </li>
    </ul>
</div>

mvcweb/Views/Shared/UserCenterNav.cshtml
<div class="nav_box">
    <ul>
        <li @(((int)Model == 0 ? " class=active" : ""))>
            <a href="@Url.Action("Home", "Home")">首页</a>
        </li>
        <li @(((int)Model == 1 ? " class=active" : ""))>
            <a href="@Url.Action("Member", "Member")">个人设置</a>
        </li>
        <li @(((int)Model == 2 ? " class=active" : ""))>
            <a href="@Url.Action("Purchase", "Purchase")">课程管理</a>
        </li>
        <li @(((int)Model == 3 ? " class=active" : ""))>
            <a href="@Url.Action("Orders", "Member")">我的订单</a>
        </li>
        <li @(((int)Model == 4 ? " class=active" : ""))>
            <a href="@Url.Action("Buy", "Purchase")">购买课程</a>
        </li>
        <li @(((int)Model == 5 ? " class=active" : ""))>
            <a href="@Url.Action("Free", "Free")">专家答疑</a>
        </li>
        <li @(((int)Model == 6 ? " class=active" : ""))>
            <a href="@Url.Action("Option", "Option")">常见问题</a>
        </li>
    </ul>
</div>

mvcweb/Views/Shared/YoungNav.cshtml
<div class="nav">
    <ul style="width: 1124px;">
        <li class="@((int)Model == 0 ? "active" : "")">
            <a href="@Url.Action("Home","Young")">首页</a>
        </li>
        <li class="@((int)Model == 1 ? "active" : "")">
            <a href="@Url.Action("Open", "Young")">免费课程</a>
        </li>
        <li class="@((int)Model == 2 ? "active" : "")">
            <a href="@Url.Action("Feature", "Young")">课程特色</a>
        </li>
        <li class="@((int)Model == 3 ? "active" : "")">
            <a href="@Url.Action("Team", "Young")">外教团队</a>
        </li>
        <li class="@((int)Model == 4 ? "active" : "")">
            <a href="@Url.Action("Free", "Young")">免费答疑</a>
        </li>
        <li class="@((int)Model == 5 ? "active" : "")">
            <a href="@Url.Action("Flow", "Young")">上课流程</a>
        </li>
        <li class="no-border @((int)Model == 6 ? "active" : "")">
            <a href="@Url.Action("Voice", "Young")">学员心声</a>
        </li>
        <li class="no-border @((int)Model == 7 ? "active" : "")">
            <a id="hidTab" href="@Url.Action("Buy", "Purchase")"></a>
        </li>
    </ul>
</div>

mvcweb/Views/Shared/_AdultLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="ABC,English online," />
    <meta name="description" content="ABC English Online Education Platform, ABC在线英语" />
    <title>ABC在线英语首页</title>
    @Styles.Render("~/bundles/styles")
</head>
<body>


    <div class="header">
        <div class="container">
            <div class="contach-info">
                <a class="email"><i></i>abc_online@abc.com.cn</a>
                <a class="tel"><i></i>400-661-9888</a>
            </div>
            <div class="logo">
                <a href="index.html"></a>
                <div class="logo-bg"></div>
            </div>
            <div class="login">
                <a class="xinlang">
                    <i></i>
                    <div class="ewm">
                        <img src="@Url.Content("~/assets/image/twodimensioncode.jpg")" />
                        <div class="appDown_title">扫码关注</div>
                    </div>
                </a>
                <a class="weixin">
                    <i></i>
                    <div class="ewm">
                        <img src="@Url.Content("~/assets/image/twodimensioncode.jpg")" />
                        <div class="appDown_title">关注Abc微信</div>
                    </div>
                </a>
            </div>
            <div class="child">
                <a href="@Url.Action("Index","Young")">切换至少儿版</a>
            </div>
            <div class="get">
                <a class="exit right-01">登录</a>
                <a class="enroll right-02">注册</a>
            </div>
            <div class="set">
                <span class="span">个人中心&nbsp;,&nbsp;</span>
                <a class="exit">退出</a>
            </div>
        </div>
    </div>

    @RenderBody()

<div class="footer">
    <div class="container">
        <i class="footer-icon"></i>
        <p class="copy">
            COPYRIGHT &copy; 2014-9-1 ABC.COM.CN, ALL RIGHTS RESERVED<br>京ICP备12029524号-1 京ICP证130137号
            京公网安备11010802012731号
        </p>
        <div class="logo-intro">
            <div class="footer-logo"></div>
        </div>
    </div>
</div>
    @Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts",false)
</body>
</html>

mvcweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>ABC在线英语</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="top">
            <div class="w1000">
                <!--left begin-->
                <div class="left flt">
                    <ul>
                        <li class="left-01"><a href="javascript:;">移动版ABC</a></li>
                        <li class="left-02"><a href="javascript:;">ABC微信</a></li>
                        <li class="left-03"><a href="javascript:;">切换至少儿版</a></li>
                        <li class="left-04">400-661-9888</li>
                    </ul>
                </div>
                <!--left end-->
                <!--right begin-->
                <div class="right frt">
                    <ul>
                        <li class="right-01"><a href="javascript:;">请登录</a></li>
                        <li class="right-02"><a href="javascript:;">立即注册</a></li>
                    </ul>
                    <div class="user hidden"></div>
                </div>
                <!--right end-->
            </div>
        </div>
        <!--top end-->
        <!--header begin-->
        <div class="header">
            <div class="w1000">
                <!--logo begin-->
                <div class="logo flt">
                    <a href="/">
                        <img src="../Images/logo.jpg" width="272" height="98" /></a>
                </div>
                <!--logo end-->
                <!--nav begin-->
                <div class="nav flt">
                    <ul>
                        <li><a target="ContentFrame" href="/Home/Home">首页</a></li>
                        <li>@Html.ActionLink("免费公开课", "Open", "Open")</li>
                        <li><a target="ContentFrame" href="/Feature/Feature">课程特色</a></li>
                        <li><a target="ContentFrame" href="/Team/Team">外教团队</a></li>
                        <li><a target="ContentFrame" href="/Free/Free">免费答疑</a></li>
                        <li><a target="ContentFrame" href="/Flow/Flow">上课流程</a></li>
                        <li><a target="ContentFrame" href="/Voice/Voice">学员心声</a></li>
                    </ul>
                    <div class="hover"></div>
                    <div class="focus"></div>
                </div>
                <!--nav end-->
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <!--footer begin-->
        <div class="footer">
            <div class="w1000">
                <!--footer-list begin-->
                <div class="footer-list" style="margin: 0 0 0 20px;">
                    <h3>ABC的优势 </h3>
                    <ul>
                        <li><a href="#">纯正英美外教</a></li>
                        <li><a href="#">一对一VIP</a></li>
                        <li><a href="#">课程内容广泛</a></li>
                        <li><a href="#">专属学习顾问</a></li>
                    </ul>
                </div>
                <!--footer-list end-->
                <!--footer-list begin-->
                <div class="footer-list">
                    <h3>ABC的实力</h3>
                    <ul>
                        <li><a href="#">二十几年线下教学经验</a></li>
                        <li><a href="#">全国三十几家连锁学校</a></li>
                        <li><a href="#">上千名优秀中外教师资</a></li>
                        <li><a href="#">数十万优秀毕业生</a></li>
                    </ul>
                </div>
                <!--footer-list end-->
                <!--footer-list begin-->
                <div class="footer-list">
                    <h3>ABC的团队</h3>
                    <ul>
                        <li><a href="#">中教团队</a></li>
                        <li><a href="#">外教团队</a></li>
                        <li><a href="#">课程顾问团队</a></li>
                        <li><a href="#">学习顾问团队</a></li>
                    </ul>
                </div>
                <!--footer-list end-->
                <!--footer-list begin-->
                <div class="footer-list">
                    <h3>帮助中心</h3>
                    <ul>
                        <li><a href="#">400客服电话</a></li>
                        <li><a href="#">在线客服</a></li>
                    </ul>
                </div>
                <!--footer-list end-->
            </div>
        </div>
        <!--footer end-->
        <!--cr begin-->
        <div class="cr">
            <p>COPYRIGHT © 2014-9-1 ABC.COM.CN, ALL RIGHTS RESERVED</p>
            <p>京ICP备12029524号-1 京ICP证130137号 京公网安备11010802012731号</p>
        </div>
        <!--cr end-->

        <!--register begin-->
        <div class="register">
            <div class="w1000">
                <div class="tips flt"><span>现在注册</span>  立即获取北美外教一对一免费体验课！</div>
                <div class="opts frt">
                    <ul>
                        <li class="opt-one"><a href="javascript:;">登陆</a></li>
                        <li class="opt-two"><a href="javascript:;">立即注册</a></li>
                    </ul>
                </div>
            </div>
            <div class="close"></div>
        </div>
        <!--register end-->

        <!--mask begin-->
        <div class="mask">
            <!--mask-title begin-->
            <div class="mask-title">
                <div class="mask-logo flt">
                    <img src="Images/maskLogo.jpg" width="125" height="60" />
                </div>
                <!--sel-title begin-->
                <div class="sel-title">
                    <ul>
                        <li id="taba1" onclick="setTab('taba',1,2)" class="hover">会员登陆</li>
                        <li id="taba2" onclick="setTab('taba',2,2)">会员注册</li>
                    </ul>
                </div>
                <!--sel-title end-->
            </div>
            <!--mask-title end-->
            <!--mask-con begin-->
            <div class="mask-con">
                <!--con-tab-1 begin-->
                <div id="con-taba-1">
                    <div id="Form1">
                        <div class="mask-tr" style="margin-top: 20px;">
                            <div class="icon email flt"></div>
                            <div style="height:40px; float:left;">
                                <input type="text" name="UserName" placeholder="请输入您注册时的E-mail账号" />
                            </div>
                        </div>
                        <div class="mask-tr">
                            <div class="icon pwd"></div>
                            <div style="height:40px; float:left;">
                                <input type="password" name="Pwd" placeholder="您的密码" />
                            </div>
                        </div>
                        <div class="mask-remember">
                            <div class="left flt">
                                <input type="checkbox" />下次自动登陆（维持14日）
                            </div>
                            <div class="right frt"><a href="javascript:;">忘记密码</a></div>
                        </div>
                        <button>登录</button>
                    </div>
                </div>
                <!--con-tab-1 end-->
                <!--con-tab-2 begin-->
                <div id="con-taba-2" style="display: none;">
                    <div id="Form2">
                        <div class="mask-tr" style="margin-top: 20px;">
                            <div class="icon email"></div>
                            <div style="height:40px; float:left;">
                                <input type="text" name="UserName" placeholder="请填写您的常用信箱，以设定登陆的用户名" />
                            </div>
                        </div>
                        <div class="mask-tr">
                            <div class="icon mobile"></div>
                            <div style="height:40px; float:left;">
                                <input type="text" name="Mobile" placeholder="请填写您的手机号码" />
                            </div>
                        </div>
                        <div class="mask-tr">
                            <div class="icon name"></div>
                            <div style="height:40px; float:left;">
                                <input type="text" name="CNName" placeholder="请填写您的姓名" />
                            </div>
                        </div>
                        <div class="mask-tr">
                            <div class="icon pwd"></div>
                            <div style="height:40px; float:left;">
                                <input type="password" name="Pwd" placeholder="请输入6~14位数字或英文的密码，不含空格" />
                            </div>
                        </div>
                        <div class="mask-tr">
                            <div class="icon pwd"></div>
                            <div style="height:40px; float:left;">
                                <input type="password" name="Pwd" placeholder="请您再次输入密码" />
                            </div>
                        </div>
                        <button>注册</button>
                    </div>
                </div>
                <!--con-tab-2 end-->
            </div>
            <!--mask-con end-->
        </div>
        <!--mask end-->

        <div class="login hidden" style="top: 50px; margin-top: 30px;">
            <ul>
                <li>***，您好</li>
                <li><a href='Member/Member' target="ContentFrame">会员中心</a></li>
            </ul>
        </div>

        <!--back begin-->
        <a href="#my-top" class="back"></a>
        <!--back end-->
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>

<script src="@Url.Content("~/js/jquery-1.8.3.min.js")"></script>
<script src="@Url.Content("~/js/base.js")"></script>
<script src="@Url.Content("~/js/jquery.cookie.js")"></script>
<script src="@Url.Content("~/js/layer/layer.js")"></script>
<script src="@Url.Content("~/js/layer/layer.js")"></script>
<script src="@Url.Content("~/js/index.js")"></script>
<script src="@Url.Content("~/js/nav.js")"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $(".right-01,.right-02,.opts li").bind("click", function () {

            $.layer({
                area: ['440px', 'auto'],
                border: [0],
                type: 1,
                title: false,
                page: { dom: '.mask' }
            });
        });
    });
    $(document).scroll(function (e, n) {
        $('.login')[0].style.top = document.body.scrollTop + 50 + 'px';
    });
    function setTab(name, cursel, n) {
        for (var i = 1; i <= n; i++) {
            var main_menu = document.getElementById(name + i);
            var sub_menu = document.getElementById('con-' + name + '-' + i);
            main_menu.className = (i == cursel) ? 'hover' : '';
            sub_menu.style.display = (i == cursel) ? 'block' : 'none';
        }
    }
</script>
</html>