mvcweb/Controllers/AbroadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcweb.Controllers
{
    public class AbroadController : Controller
    {
        //
        // GET: /Abroad/

        public ActionResult Index()
        {

            ViewBag.PicUrl = System.Configuration.ConfigurationManager.AppSettings["studyabroad"];
            return View();
        }

        public ActionResult Train()
        {
            return View();
        }
    }
}

mvcweb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using Service;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;
using ThoughtWorks.QRCode.Codec;
using System.Drawing;
using System.Text;
using System.Drawing.Imaging;
using WxPayAPI;

namespace mvcweb.Controllers
{
    public class HomeController : BascVirtualController
    {
        MemberService service = new MemberService();
        WebPageService pageSrv = new WebPageService();
        BuyClassService bugService = new BuyClassService();


        public ActionResult WeiXinPayImgPath(int OrderId)
        {
 
          //  var str = Common.GetDistanceInfo("http://www.gistoyou.com/MOBILE/pay/GetQRCode", "{\"OrderId\":\"" + OrderId + "\"}");
            var str = GetPayUrl(OrderId.ToString());
 
            //string url = System.Configuration.ConfigurationManager.AppSettings["SsoUrl"];
            //var str = Common.GetDistanceInfo(url+"/pay/GetQRCode", "{\"OrderId\":\"" + OrderId + "\"}");
 

            //初始化二维码生成工具
            QRCodeEncoder qrCodeEncoder = new QRCodeEncoder();
            qrCodeEncoder.QRCodeEncodeMode = QRCodeEncoder.ENCODE_MODE.BYTE;
            qrCodeEncoder.QRCodeErrorCorrect = QRCodeEncoder.ERROR_CORRECTION.M;
            qrCodeEncoder.QRCodeVersion = 0;
            qrCodeEncoder.QRCodeScale = 4;

            //将字符串生成二维码图片
         //   Bitmap image = qrCodeEncoder.Encode(JObject.Parse(str).Last.Last.Last.Values().First().ToString(), Encoding.Default);

            Bitmap image = qrCodeEncoder.Encode(str, Encoding.Default);

            //保存为PNG到内存流  
            MemoryStream ms = new MemoryStream();
            image.Save(ms, ImageFormat.Png);

            return File(ms.GetBuffer(), "image/png");
        }

        public ActionResult Index()
        {
            var usercookies = HttpContext.Request.Cookies.Get("logininfo");
            var userId = "";
            if (usercookies != null)
            {
                if (!string.IsNullOrEmpty(usercookies.Value))
                {
                    var userinfo = Common.DesEncrypt(usercookies.Value);
                    userinfo = HttpUtility.UrlDecode(userinfo, System.Text.Encoding.GetEncoding("UTF-8"));
                    var usemerminfo = JsonConvert.DeserializeObject<MemberDto>(userinfo);
                    userId = usemerminfo.Id.ToString();
                }
            }
            ViewBag.Id = userId;
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult Home()
        {
            ViewBag.Path = GetBaseVirtualPath;
            ViewBag.VideoUrl = System.Configuration.ConfigurationManager.AppSettings["videourl"];
            return View();
        }

        public ActionResult TeacherLogin()
        {
            var path= GetBaseVirtualPath;
            ViewBag.Path = path;
            return View();
        }

        public ActionResult Teacher()
        {
            var path = GetBaseVirtualPath;
            return View();
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteType">0:成人版，1：少年版</param>
        /// <param name="typeId">1：首页，2：免费课程，3：课程特色，4：外教团队，5：在线答疑，6：上课流程，7：学员心声</param>
        /// <returns></returns>
        public ActionResult GetWebSiteImages(int siteType, int typeId)
        {
            return Json(pageSrv.GetPageImages(siteType, typeId));
        }

        [HttpPost]
        public ActionResult GetArtcleForFooter()
        {
            var list = pageSrv.GetArtListForFooter();
            var ret = list != null && list.Count > 0;
            return Json(new { ret = ret, obj = list });
        }
        public ActionResult Login(string userName, string Pwd, bool isSave)
        {
            var member = new Member()
            {
                UserName = userName,
                Pwd = Common.Encrypt(Pwd)
            };
            var obj = service.Login(member);

            if (obj.IsSuccess)
            {
                SignCookie(obj.Result, isSave);
            }

            return Json(new Response<MemberDto> { Result = obj.IsSuccess ? ConvertMember(obj.Result) : null, ErrMsg = obj.ErrMsg });
        }

        public ActionResult MemberTeacherLogin(string userName, string Pwd, bool isSave)
        {
            var member = new Member()
            {
                UserName = userName,
                Pwd = Common.Encrypt(Pwd)
            };
            var obj = service.TeacherLogin(member);

            if (obj.IsSuccess)
            {
                SignCookie(obj.Result, isSave);
            }

            return Json(new Response<MemberDto> { Result = obj.IsSuccess ? ConvertTeacherMember(obj.Result) : null, ErrMsg = obj.ErrMsg });
        }

        private MemberDto ConvertMember(Member member)
        {
            return new MemberDto
            {
                Id = member.Id,
                Name = !string.IsNullOrEmpty(member.CNName) ? member.CNName : !string.IsNullOrEmpty(member.ENName) ? member.ENName : member.Mobile,
                Type = member.MemberType,
                Logo = member.Logo
            };
        }

        private MemberDto ConvertTeacherMember(Member member)
        {
            return new MemberDto
            {
                Id = member.Id,
                Name = !string.IsNullOrEmpty(member.ENName) ? member.ENName :member.UserName,
                Type = member.MemberType,
                Logo = member.Logo
            };
        }

        public ActionResult LoginOut()
        {
            var cookie = HttpContext.Response.Cookies.Get("logininfo");
            cookie.Expires = DateTime.Now;
            HttpContext.Response.SetCookie(cookie);
            return Json(new Response<bool>());
        }

        public ActionResult GetLogin()
        {
            var obj = new Response<MemberDto>();
            try
            {
                obj.Result = Common.GetCurrentUser(HttpContext);

                if (obj.Result == null)
                {
                    obj.ErrMsg = "未登录";
                }
                else
                {
                    obj.Result = ConvertMember(new MemberService().GetMember(obj.Result.Id).Result);
                }
            }
            catch (Exception ex)
            {
                DataBase.DbHelperSQL.WriteLog("用户自动登录异常", ex);
                obj.ErrMsg = "未登录";
            }
            return Json(obj);
        }

        public ActionResult GetTeacherLogin()
        {
            var obj = new Response<MemberDto>();
            try
            {
                obj.Result = Common.GetCurrentUser(HttpContext);

                if (obj.Result == null)
                {
                    obj.ErrMsg = "Not signed";
                }
                else
                {
                    obj.Result = ConvertMember(new MemberService().GetMember(obj.Result.Id).Result);
                }
            }
            catch (Exception ex)
            {
                DataBase.DbHelperSQL.WriteLog("用户自动登录异常", ex);
                obj.ErrMsg = "Not signed";
            }
            return Json(obj);
        }
        public ActionResult Error()
        {
            return View();
        }

        public ActionResult Register(string user, string pwd, int userType, string valid)
        {
            var res = new Response<MemberDto>();
            if (Session["uuid"] != null && service.ExistMemberValid(user, Session["uuid"].ToString(), valid))
            {
                if (!service.ExistMember(user))
                {
                    var obj = service.Register(new Member
                    {
                        Mobile = user,
                        UserName = user,
                        MemberType = userType,
                        Pwd = Common.Encrypt(pwd)
                    });

                    if (obj.IsSuccess)
                    {
                        SignCookie(obj.Result);
                    }
                    res.ErrMsg = obj.ErrMsg;
                    res.Result = obj.IsSuccess ? ConvertMember(obj.Result) : null;
                }
                else
                {
                    res.ErrMsg = "用户电话号码已注册！您可以找回密码!";
                }
            }
            else
            {
                res.ErrMsg = "验证码无效！请重新获取验证码！";
            }
            return Json(res);
        }

        public ActionResult ModifyPassword(string user, string pwd, string valid)
        {
            var res = new Response<MemberDto>();
            if (Session["uuid"] != null && service.ExistMemberValid(user, Session["uuid"].ToString(), valid))
            {
                var member = DataBase.DbHelperSQL.ExcuteScaler<Member>("select * from Member where username=@0", user).FirstOrDefault();
                if (member != null)
                {
                    var obj = service.UpdatePassword(member.Id, member.Pwd, Common.Encrypt(pwd));
                    if (obj.IsSuccess)
                    {
                        SignCookie(member);
                    }
                    res.Result = obj.IsSuccess ? ConvertMember(member) : null;
                    res.ErrMsg = obj.ErrMsg;
                }
                else
                {
                    res.ErrMsg = "用户名不存在！";
                }
            }
            else
            {
                res.ErrMsg = "验证码无效！请重新获取验证码！";
            }
            return Json(res);
        }

        public ActionResult ModifyPasswordForTeacher(string user, string pwd, string valid)
        {
            var res = new Response<MemberDto>();
            if (Session["uuid"] != null && service.ExistMemberValid(user, Session["uuid"].ToString(), valid))
            {
                var member = DataBase.DbHelperSQL.ExcuteScaler<Member>("select * from Member where username=@0", user).FirstOrDefault();
                if (member != null)

mvcweb/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcweb.Controllers
{
    public class TeacherController : Controller
    {


        public ActionResult ChangePassword()
        {
            return View();
        }

        public ActionResult CourseList()
        {
            return View();
        }

        public ActionResult CourseTable()
        {
            return View();
        }

        public ActionResult Evaluate()
        {
            return View();
        }


    }
}

mvcweb/Controllers/YoungController.cs
using Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcweb.Controllers
{
    public class YoungController : BascVirtualController
    {
        //
        // GET: /Young/

        public ActionResult Feature()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult Home()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }

        public ActionResult Flow()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Free()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Index()
        {
            var usercookies = HttpContext.Request.Cookies.Get("logininfo");
            var userId = "";
            if (usercookies != null)
            {
                if (!string.IsNullOrEmpty(usercookies.Value))
                {
                    var userinfo = Common.DesEncrypt(usercookies.Value);
                    userinfo = HttpUtility.UrlDecode(userinfo, System.Text.Encoding.GetEncoding("UTF-8"));
                    var usemerminfo = JsonConvert.DeserializeObject<MemberDto>(userinfo);
                    userId = usemerminfo.Id.ToString();
                }
            }
            ViewBag.Id = userId;
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Model()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Open()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Team()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
        public ActionResult Voice()
        {
            ViewBag.Path = GetBaseVirtualPath;
            return View();
        }
    }
}

mvcweb/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="ABC,English online," />
    <meta name="description" content="ABC English Online Education Platform, ABC在线英语" />
    <title>ABC在线英语首页</title>
    <link href="~/Content/commen.css" rel="stylesheet" />
    <link href="~/static/css/index.css" rel="stylesheet" />
    <link href="~/static/css/login.css" rel="stylesheet" />
    <link href="~/assets/css/choosepage.css" rel="stylesheet" />
    <link href="~/assets/css/StyleSheet1.css" rel="stylesheet" />
    <link href="~/Content/adult/index.css" rel="stylesheet" />
    <style>
        .layui-layer-setwin .layui-layer-close2 {
            right: 0;
            top: 0;
            background-image: (@Url.Content("~/image/login/close_btn.png"))
        }
        #login {
            padding: 30px;
        }
         .logo {
            margin: auto;
            display: block;
            padding: 30px;
        }
         .login_form {
            background-color: #F6F6F6;
            padding: 20px;
        }
         .mask-input{
            margin: 10px 20px;
        height: 40px;
    line-height: 40px;
        }
         .mask-input input:not([type="checkbox"]){
            width: 307px;
            height: 40px;
            outline: hidden;
            padding: 0 0 0 10px;
        }
         button{font-size: 16px;
    width: 307px;
    height: 42px;
    background: #C7151D;
    color: #FFF;
    border: none;
    display: block;
    margin: 20px;
    margin-bottom: 30px;
    cursor: pointer;
        }
        .frt::after {
            clear: both;
        }
    </style>
</head>
<body>


    <div class="header">
        <div class="container">
            <div class="contach-info">
                <a class="email"><i></i>abc_online@abc.com.cn</a>
                <a class="tel"><i></i>400-661-9888</a>
            </div>
            <div class="logo">
                <a href="@Url.Action("Index")"></a>
                <div class="logo-bg"></div>
            </div>
            <div class="login">
                <a class="xinlang">
                    <i></i>
                    <div class="ewm">
                        <img src="@Url.Content("~/assets/image/twodimensioncode.jpg")" />
                        <div class="appDown_title">扫码关注</div>
                    </div>
                </a>
                <a class="weixin">
                    <i></i>
                    <div class="ewm">
                        <img src="@Url.Content("~/assets/image/twodimensioncode.jpg")" />
                        <div class="appDown_title">关注Abc微信</div>
                    </div>
                </a>
            </div>
            <div class="child">
                <a href="@Url.Action("Index","Young")">切换至少儿版</a>
            </div>
            <div class="get">
                <a class="exit">登录</a>
                <a class="enroll">注册</a>
            </div>

            <div class="user hidden" style="float: right; margin: 0 20px;"><span></span><span></span></div>
        </div>
    </div>

    <iframe name="ContentFrame" id="ContentFrame" style="min-width: 1140px; width: 100%; height: 2200px; border: 0px;" scrolling="no" frameborder="0" src="@Url.Action("Home","Home")"></iframe>



    <div class="choose-page" style="display: none;">
        <div class="choose-page-bg"></div>
        <div class="all-page-types">
            <div class="page-type adult">
                <div class="bg"></div>
                <div class="mask"></div>
                <div class="intro">
                    <p class="title-en">ADULT<br />ENGLISH</p>

                    <p class="title-zh">成人英语</p>

                    <p class="content-varied"><a href="javascript:void(0);">点击进入</a></p>
                    <p style="margin-top: 15px;">王牌零起点<br/>基础新概念<br/>生存口语<br/>生活口语<br/>商务口语</p>
                </div>
            </div>
            <div class="page-type young active">
                <a href="@Url.Action("Index","Young")" style="color: #fff;">
                    <div class="bg"></div>
                    <div class="mask"></div>
                    <div class="intro">
                        <p class="title-en">YOUNG<br />ENGLISH</p>

                        <p class="title-zh">少儿英语</p>
                        <p class="content-varied"><a href="javascript:void(0);">点击进入</a></p>

                        @*<p class="content-varied">6-18岁<br>二十年线下<br>青少年教学经验</p>*@
                        <p style="margin-top: 15px;">趣味音标<br />兴趣语法<br />基础英语<br />外教口语</p>
                    </div>
                </a>
            </div>
            <div class="page-type overseas">
                <div class="bg"></div>
                <div class="mask"></div>
                <div class="intro">
                    <p class="title-en">STUDY<br />TRAIN</p>

                    <p class="title-zh">留学直通车</p>

                    <p class="content-varied"><a class="choose-page-link" href="@Url.Action("Index", "Abroad")">点击进入</a></p>
                    <p style="margin-top: 15px;">原版教材<br />学科英语<br />托福辅导<br />雅思辅导</p>
                </div>
            </div>
            <div class="page-type corporate">
                <div class="bg"></div>
                <div class="mask"></div>
                <div class="intro">
                    <p class="title-en">CORPORATE<br />TRAINING</p>

                    <p class="title-zh">企业培训</p>

                    <p class="content-varied"><a class="choose-page-link" href="@Url.Action("Train", "Abroad")">点击进入</a></p>
                    <p style="margin-top: 15px;">量身制定<br />教材<br />线上线下<br />结合</p>
                </div>
            </div>
        </div>
    </div>

    <!--mask begin-->
    <div id="login" style="display: none;">
        <div>
            <img class="logo" src="~/Content/image/logo.png" />
        </div>
        <div class="login">
            <div id="Form1" class="login_form">
                <div class="mask-input">
                    <input id="login_name" name="UserName" type="text" placeholder="请输入您的手机号码" />
                </div>
                <div class="mask-input">
                    <input id="login_pwd" type="password" placeholder="密码" />
                </div>
                <div class="mask-input">
                    <div class="frt">
                        <input id="login_auto" class="autologin" type="checkbox" />
                        <label for="login_auto">自动登录</label>
                    </div>
                </div>
                <button method="login" id="login_btn" class="mask-input">登录</button>
                <div class="mask-input">
                    <a style="color: #c7151d" href="javascript:searchPassword();">忘记密码</a>
                </div>
            </div>
            <div style="margin: 0 auto; text-align: center;padding-top: 15px;">
                还不是会员？<a id="login_register" style="color: #c7151d">注册</a>
            </div>
        </div>
        <div class="register" id="Form2">
            <div class="login_form">
                <div class="mask-input">
                    <input id="reg_" type="text" name="UserName" placeholder="请输入您的手机号码" />
                </div>
                <div class="mask-input">
                    <input id="reg_pwd" type="password" placeholder="密码" />
                </div>
                <div class="mask-input" style=" margin 0 20px; line-height inherit; height auto;">
                    请输入6-14位数字或英文的密码，不含空格
                </div>
                <div class="mask-input">
                    <input id="reg_pwd2" type="password" placeholder="请您再次输入密码" />
                </div>
                <div class="mask-input">
                    <input type="text" name="Validate" style="padding-left: 10px; float: left; height: 40px; width: 150px; border: 1px solid #ddd;" placeholder="请填写手机验证码">
                    <button method="sendValid" data="1" style="width: 150px; height: 40px;">获取验证码</button>
                </div>
                <button method="register">注册</button>
            </div>
            <div style="margin: 0 auto; text-align: center;padding-top: 15px;">
                已经拥有账户？<a id="register_login" style="color: #c7151d">登陆</a>
            </div>
        </div>
    </div>
    <!--mask end-->

    <div class="mask searchPassword hidden layui-layer-wrap" style="display: none; padding: 0 30px;">
        <div style="display: block; padding: 30px; margin: auto;">
            <img src="~/Content/image/logo.png" style="margin: auto; display: block;">
        </div>
        <div class="login_form">
            <div style="width: 100%; height: 10px"></div>
            <div class="mask-input">
                <input type="text" name="UserName" placeholder="请填写您的手机号码">
            </div>
            <div class="mask-input">
                <input type="password" name="Pwd" placeholder="设置新密码">
            </div>
            <div class="mask-input">
                <input type="password" name="Pwd" placeholder="请您再次输入密码">
            </div>
            <div class="mask-input">
                <input type="text" name="Validate" style="padding-left: 10px; float: left; height: 40px; width: 150px; border: 1px solid #ddd;" placeholder="请填写手机验证码">
                <button method="sendValid" data="2" style="width: 150px; height: 40px;">获取验证码</button>
            </div>
            <button method="modifyPassword">修改密码</button>
        </div>

    </div>


    <div class="footer">
        <div class="container">
            <i class="footer-icon"></i>
            <p class="copy">
                COPYRIGHT &copy; 2014-9-1 ABC.COM.CN, ALL RIGHTS RESERVED<br>京ICP备12029524号-1 京ICP证130137号
                京公网安备11010802012731号
            </p>
            <div class="logo-intro">
                <div class="footer-logo"></div>
            </div>
        </div>
    </div>

    <div class="fixed-register" style="display: none;">
        <div class="container">
            <div class="tips">立即注册，领取价值1000元新生课程礼包</div>
            <div class="buttons">立即领取</div>
        </div>
    </div>

    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/abc/base.es5.min.js"></script>
    <script src="~/Scripts/jquery.cookie.js"></script>
    <script src="~/Scripts/layer/layer.js"></script>
    <script src="~/Scripts/abc/common.es5.min.js"></script>
    <script src="~/Scripts/abc/index.es5.js"></script>

    <script src="~/Scripts/abc/easemobIM.js"></script>
    <script src="~/Scripts/easemob.js"></script>
</body>
</html>

mvcweb/Views/Home/Teacher.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="ABC,English online," />
    <meta name="description" content="ABC English Online Education Platform, ABC在线英语" />
    <title>ABC在线英语首页</title>
    <link href="~/Content/commen.css" rel="stylesheet" />
    <link href="~/static/css/index.css" rel="stylesheet" />
    <link href="~/static/css/login.css" rel="stylesheet" />
    <link href="~/assets/css/choosepage.css" rel="stylesheet" />
    <link href="~/assets/css/StyleSheet1.css" rel="stylesheet" />

</head>
<body>
    <div class="header">
        <div class="container">
            <div class="contach-info">
                <a class="email"><i></i>abc_online@abc.com.cn</a>
                <a class="tel"><i></i>400-661-9888</a>
            </div>
            <div class="logo">
                <a href="@Url.Action("Index","Home")"></a>
                <div class="logo-bg"></div>
            </div>
            <div class="login">
                <a class="xinlang">
                    <i></i>
                    <div class="ewm">
                        <img src="@Url.Content("~/assets/image/twodimensioncode.jpg")" />
                        <div class="appDown_title">扫码关注</div>
                    </div>
                </a>
                <a class="weixin">
                    <i></i>
                    <div class="ewm">
                        <img src="@Url.Content("~/assets/image/twodimensioncode.jpg")" />
                        <div class="appDown_title">关注Abc微信</div>
                    </div>
                </a>
            </div>
            <div class="child">
                <a href="@Url.Action("Index","Young")">切换至少儿版</a>
            </div>
            @*<div class="get">
                    <a class="exit">登录</a>
                    <a class="enroll">注册</a>
                </div>*@
            <div class="set">
                <span class="span">个人中心&nbsp;,&nbsp;</span>
                <a class="exit">退出</a>
            </div>
            <div class="user hidden" style="float: right; margin: 0 20px;"><span></span><span></span></div>
        </div>
    </div>

    <iframe name="ContentFrame" id="ContentFrame" style="width: 100%; height: 600px; border: 0;" scrolling="no" src="@Url.Action("TeacherLogin","Home")"></iframe>




    <div class="footer">
        <div class="container">
            <i class="footer-icon"></i>
            <p class="copy">
                COPYRIGHT &copy; 2014-9-1 ABC.COM.CN, ALL RIGHTS RESERVED<br>京ICP备12029524号-1 京ICP证130137号
                京公网安备11010802012731号
            </p>
            <div class="logo-intro">
                <div class="footer-logo"></div>
            </div>
        </div>
    </div>

    <script src="@ViewBag.Path/js/jquery-1.8.3.min.js"></script>
    <script src="@ViewBag.Path/js/base.js"></script>
    <script src="@ViewBag.Path/js/jquery.cookie.js"></script>
    <script src="@ViewBag.Path/js/layer/layer.js"></script>
    <script src="@ViewBag.Path/js/nav.js"></script>
    @*<script src="@ViewBag.Path/js/common.js"></script>*@
    @*<script src="@ViewBag.Path/js/teacherlogin.js"></script>*@
    @*<script src="@ViewBag.Path/js/nav.js"></script>*@
    <script>


        window.loginOut = function () {
            $.ajax({
                url: $.url + '/Home/LoginOut',
                data: Math.random(),
                type: 'post',
                dataType: 'json',
                success: function (rel) {
                    if (rel.IsSuccess) {
                        window.location.href = window.location.href;
                    }
                }
            });
        }
        window.updateContentFrameHeight = function (height) {
            $('#ContentFrame').css({
                height: height
            });
        };

        window.showMessage = function (tip, message) {
            layer.alert(message,
            {
                icon: tip || 1,
                skin: 'layer-ext-moon' //该皮肤由layer.seaning.com友情扩展。关于皮肤的扩展规则，去这里查阅
            });
        };

    </script>
</body>
</html>

mvcweb/Views/Home/TeacherLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="ABC,English online," />
    <meta name="description" content="ABC English Online Education Platform, ABC在线英语" />
    <title>ABC Online</title>
    <link href="~/assets/css/common.css" rel="stylesheet"/>
    <link href="~/assets/css/login.css" rel="stylesheet" />
    <link href="~/assets/css/StyleSheet1.css" rel="stylesheet" />
</head>
<body>
    <div id="login" style="margin-top: 50px;">
        @*<div>
            <img class="logo" src="~/image/login/logo.png" />
        </div>*@
        <div class="login login-popup">
            <div id="Form1" class="login_form">
                <div class="text-center">
                    Teacher Login
                </div>
                <div class="mask-input">
                    <input id="login_name" name="UserName" type="text" placeholder="please enter your name" />
                </div>
                <div class="mask-input">
                    <input id="login_pwd" type="password" placeholder="please enter your password" />
                </div>
                <div class="mask-input">
                    <div class="frt">
                        <input id="login_auto" class="autologin" type="checkbox" />
                        <label for="login_auto">Auto Login</label>
                    </div>
                </div>
                <button method="login" id="login_btn" class="mask-input" style="width:300px;">Login</button>
                <div class="mask-input">
                    <a style="color: #c7151d" href="javascript:searchPassword();">Forget password?</a>
                </div>
            </div>
            <div style="margin: 0 auto; text-align: center;text-align: center;padding-top: 15px;">
                Not a member？<a id="login_register" style="color: #c7151d">register</a>
            </div>
        </div>

    </div>
    <div class="mask searchPassword hidden layui-layer-wrap  login-popup " style=" display:none; padding:30px 30px;">
        <div style="display: block; padding: 30px; margin: auto;">
            <img src="~/Content/image/logo.png" style="margin: auto; display: block;">
        </div>
        <div class="login_form">
            <div style="width: 100%; height: 10px"></div>
            <div class="mask-input">
                <input type="text" name="UserName" placeholder="please enter your phone number">
            </div>
            <div class="mask-input">
                <input type="password" name="Pwd" placeholder="Set a new password">
            </div>
            <div class="mask-input">
                <input type="password" name="Pwd" placeholder="Please enter your password again">
            </div>
            <div class="mask-input">
                <input type="text" name="Validate" style="padding-left: 10px; float: left; height: 40px; width: 250px; border: 1px solid #ddd;" placeholder="Please entry the sms verification code">
                <button method="sendValid" data="2" style="width: 150px; height: 40px;">Verification code</button>
            </div>
            <button method="modifyPassword">Modify password</button>
        </div>

    </div>
    <script src="@ViewBag.Path/js/jquery-1.8.3.min.js"></script>
    <script src="@ViewBag.Path/js/base.js"></script>
    <script src="@ViewBag.Path/js/jquery.cookie.js"></script>
    <script src="@ViewBag.Path/js/layer/layer.js"></script>
    <script src="@ViewBag.Path/js/common.js"></script>
    <script src="@ViewBag.Path/js/teacherlogin.js"></script>
    @*<script src="@ViewBag.Path/js/nav.js"></script>*@
</body>
</html>